name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: lifematch-api-dev

    steps:
    - uses: actions/checkout@v2
    - name: Build the Dev Docker image
      run: | 
            ls
            docker build . --file Dockerfile --tag lifematch-api-dev:1
            docker ps -q --filter "name=lifematch-api-dev-container" | grep -q . && docker stop lifematch-api-dev-container && docker rm -fv lifematch-api-dev-container
            docker run --name lifematch-api-dev-container -e NODE_ENV=local --env-file $HOME/actions-runner/_work/lifematch-api/env.list -v $HOME/volumes/proflie-uploads:/usr/src/app/proflie-uploads -d -p 8083:8083 --restart=always lifematch-api-dev:1